name: lsr_ludo_king
description: LSR Ludo King Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_mobile_ads: ^3.1.0

flutter:
  uses-material-design: true
