name: ludo_reward_app_flutter
description: A Flutter Ludo Reward App Starter
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.13.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^5.7.0
  google_mobile_ads: ^3.3.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
